Repository googleapis/java-profiler, pull requests merged in 2021-04, with the labels that each got.

#25 chore(java): add deprecation warning template to readme
  .github/sync-repo-settings.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#16 chore: remove README gen from primary synth
  synth.py
Labels: api: cloudprofiler, automerge, cla: yes

#33 fix: fix version in versions.txt
  versions.txt
Labels: api: cloudprofiler, cla: yes

#37 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes

#44 fix: release scripts from issuing overlapping phases
  .kokoro/build.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#46 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes

#51 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes, kokoro:force-run

#56 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes

#57 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes
