Repository googleapis/java-profiler, pull requests merged in 2021-05, with the labels that each got.

#59 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudprofiler, automerge, cla: yes

#61 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#62 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#67 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#68 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes, kokoro:force-run

#69 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes

#70 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#71 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#75 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full

#80 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes

#81 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudprofiler, automerge, cla: yes
